title: Embodied AI Blog
description: Posts about Embodied AI: a path to AGI
url: https://eai.one
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
show_downloads: false
google_analytics: G-BB4KPHFR84
